### PR TITLE
Support Antiatomic

### PR DESCRIPTION
**Pull request by SriMethan**

### CODE REVIEW

**Comment by TheYoBots** [comment]
antiatomic rules weren't even followed in this PR.

**Comment by SriMethan** [comment]
> antiatomic rules weren't even followed in this PR.

Yes, of course.

**Comment by SriMethan** [comment]
I guess there should be 
```ini
blastOnCapture = true
```

**Comment by TheYoBots** [comment]
> I guess there should be
> 
> ```ini
> blastOnCapture = true
> ```

No, that should definately not be added. I'll create a PR as soon as I can to fix this.

**Comment by SriMethan** [comment]
> > I guess there should be
> > ```ini
> > blastOnCapture = true
> > ```
> 
> No, that should definately not be added. I'll create a PR as soon as I can to fix this.

btw https://github.com/RaviharaV-bot/Liantichess/pull/12 should be fine I guess, although I haven't tested it

**Comment by TheYoBots** [comment]
> > > I guess there should be
> > > ```ini
> > > blastOnCapture = true
> > > ```
> > 
> > 
> > No, that should definately not be added. I'll create a PR as soon as I can to fix this.
> 
> btw #12 should be fine I guess, although I haven't tested it

Losts of unneeded code in #12 

https://github.com/ianfab/Fairy-Stockfish/blob/c96acb864bd52fb440a0ae280010d1259e40dfb2/src/variants.ini#L268-L270 just need to copy paste that. Though I prefer the atomic oriented version.

**Comment by SriMethan** [comment]
> > I guess there should be
> > ```ini
> > blastOnCapture = true
> > ```
> 
> No, that should definately not be added. I'll create a PR as soon as I can to fix this.

if possible send a pr please

**Pull request merged**
